#!/usr/bin/env bash
# nginx installation on a server

sudo apt update
sudo apt -y install nginx

sudo service nginx start

dir="/var/www/html"
if [ -d "$dir" ]; then
        touch /var/www/html/index.html
        echo "Hello World!" >> /var/www/html/index.html
else
        echo "Problem in parsing the code"
fi
sudo service nginx restart
