#!/usr/bin/env bash
# nginx installation on a server

sudo apt update
sudo apt -y install nginx

sudo service nginx start

sudo sed -i 's/^\(.*listen.*\)80/\180/' /etc/nginx/sites-available/default

sudo service nginx restart

dir="/var/www/html"
if [ -d "$dir" ]; then
        touch /var/www/html/index.html
        echo "Hello World!" >> /var/www/html/index.html
else
        echo "Problem in parsing the code"
fi
