#!/usr/bin/env bash
# Nginx configuration

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "15i \\\tadd_header X-Served-By \$(hostname);" /etc/nginx/nginx.conf
sudo service nginx restart
