#!/usr/bin/env bash
# This scripts sets up and configure haproxy on a server
sudo apt -y update
sudo apt -y upgrade

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo systemctl start haproxy

echo "frontend http
	bind *:80
	mode http

	default_backend web-backend

backend web-backend
	balance roundrobin
        server web-01 100.27.13.122:80 check
        server web-02 54.236.12.237:80 check" >> /etc/haproxy/haproxy.cfg


sudo systemctl restart haproxy

echo -e "DONE.\n"
