#!/usr/bin/env bash
# Load balancer server setup

sudo apt update
sudo apt upgrade -y

sudo apt install -y haproxy

haproxy_config="/etc/haproxy/haproxy.cfg"
sudo cp "$haproxy_config" "$haproxy_config.bak"

sudo tee "$haproxy_config" > /dev/null <<EOL
global
    log /dev/log local0
    log /dev/log local1 notice
    daemon

defaults
    log global
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend webapp
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOL

sudo haproxy -f "$haproxy_config" -c

sudo systemctl restart haproxy
