#!/usr/bin/env bash
# This Loops from 1 to 10 and
# 'bad luck' is displayed on 4th loop iteration,
# 'good luck' is displayed on 8th loop iteration, and
# 'Best School' for the others

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	
	(( i+=1 ))
done
