#!/usr/bin/env bash
# configure your unbuntu servers with desired ip
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo '8.8.8.8	facebook.com' >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
